site_name: CM++ Pipeline Documentation
theme: cinder
nav:
  - Quick Start:
    - Features: features.md
    - Installation: installation.md
    - Quick Start Guide: quickstart.md
  - Input and Usage:
    - Example Commands: examples.md
    - CM++ Usage: cmpp.md
    - CM Pipeline Usage: pipeline_usage.md
    - JSON Format Tutorial: json_format.md
  - Contributing:
    - Developer Setup: dev_setup.md